### ISSUE TITLE
Can't follow symlink without -L/--copy-links

### ISSUE THREAD

**Issue by JmzTaylor** [pfidr34/docker-rclone#14]
I am using this in a docker-compose and getting this filling the logs.  Adding that to `SYNC_OPTS` doesn't fix the issue.  Am I just reading the documentation wrong?

**Comment by pfidr34** [comment]
@JmzTaylor can you post your full docker compose for this container please?

**Comment by JmzTaylor** [comment]
> @JmzTaylor can you post your full docker compose for this container please?

    rclone:
    container_name: rclone
    image: pfidr/rclone:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      UID: ${PUID}
      GID: ${PGID}
      SYNC_SRC: "/source"
      SYNC_DEST: "drive:"
      CRON: "@hourly"
      FORCE_SYNC: 1
      RCLONE_CMD: "copy"
    volumes:
       - /media/config/rclone:/config
       - /media/config:/source

**Comment by pfidr34** [comment]
Thanks, I'll take a look this weekend.

Here is a discussion about this topic from the rclone github:
https://github.com/rclone/rclone/issues/1152

**Comment by pfidr34** [comment]
@JmzTaylor, it took some fiddling and understanding of how docker handles symlinks for volumes but I was able to get this working by using the `--copy-links` flag in `SYNC_OPTS`.

The important part is that the symlinks are relative path links so they can be interpreted inside the container.

Example:

`ln -s /mnt/SSD_STRGE/TEMP/D /mnt/SSD_STRGE/TEMP/E`

This will fail in the container because the reference for folder E is `/mnt/SSD_STRGE/TEMP/D` however the path `/mnt/SSD_STRGE/TEMP` does not exist in the container.

This however will work inside the container:
```
cd /mnt/SSD_STRGE/TEMP
ln -s ./D ./E 
```

See docker-copose:
```
rclone_test:
    image: "rclone_test"
    container_name: "rclone_test"
    volumes:
      - ${USERDIR}/docker/rclone_test:/config
      - ${USERDIR}/docker/rclone_test/logs:/logs
      - /mnt/SSD_STRGE/TEMP:/mnt/TEMP
    environment:
      - UID=1000
      - GID=1000
      - CRON=@daily
      - RCLONE_CMD=copy
      - SYNC_DEST=GDrive:/1
      - SYNC_SRC=/mnt/TEMP
      - SYNC_OPTS=--copy-links -v
      - RCLONE_DIR_CMD=lsf
      - OUTPUT_LOG=1
      - FORCE_SYNC=1
      - TZ=${TZ}
```
